tasks/urls.py
from django.urls import path
from tasks.views import (
    TaskCreateView,
    TaskListView,
    complete_task,
    update_status,
    TaskUpdateView,
    TaskDetailView,
    post_comment,
    search_task,
)


urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", complete_task, name="complete_task"),
    path("<int:pk>/status/", update_status, name="update_status"),
    path("<int:pk>/edit/", TaskUpdateView.as_view(), name="update_task"),
    path("<int:pk>/", TaskDetailView.as_view(), name="show_task"),
    path("<int:pk>/comment/", post_comment, name="post_comment"),
    path("search/", search_task, name="search_task"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
]

tasks/models.py
from django.db import models
from django.conf import settings

# from tasks.choices import STATUS_CHOICES

USER_MODEL = settings.AUTH_USER_MODEL

STATUS_CHOICES = (
    ("OPEN", "OPEN"),
    ("IN PROGRESS", "IN PROGRESS"),
    ("PENDING", "PENDING"),
    ("NEEDS FOLLOW UP", "NEEDS FOLLOW UP"),
    ("DROPPED", "DROPPED"),
    ("COMPLETED", "COMPLETED"),
    ("CLOSED", "CLOSED"),
)

PRIORITY_CHOICES = (
    ("URGENT", "URGENT"),
    ("HIGH", "HIGH"),
    ("Normal", "Normal"),
    ("Low", "Low"),
)


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    date_completed = models.DateTimeField(blank=True, null=True)
    project = models.ForeignKey(
        "projects.Project",
        related_name="tasks",
        on_delete=models.CASCADE,
    )
    assignee = models.ForeignKey(
        USER_MODEL,
        related_name="tasks",
        null=True,
        on_delete=models.SET_NULL,
    )
    notes = models.TextField(blank=True, null=True)
    status = models.CharField(
        max_length=15, choices=STATUS_CHOICES, default="OPEN"
    )
    priority = models.CharField(
        max_length=6, choices=PRIORITY_CHOICES, default="Normal"
    )

    def __str__(self):
        return self.name


# https://djangocentral.com/creating-comments-system-with-django/
class Comment(models.Model):
    task = models.ForeignKey(
        "Task", related_name="comments", on_delete=models.CASCADE
    )
    commenter = models.ForeignKey(
        USER_MODEL,
        related_name="comments",
        null=True,
        on_delete=models.PROTECT,
    )
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return "Comment: " + str(self.body) + " by " + str(self.commenter)

tasks/forms.py
from tasks.models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    # https://docs.djangoproject.com/en/4.0/topics/forms/modelforms/#overriding-the-default-fields
    # These 3 lines below have exactly the same effect as lines 14-17
    # body = forms.CharField(
    #     label="", widget=forms.Textarea(attrs={"rows": 4, "cols": 120})
    # )

    class Meta:
        model = Comment
        fields = ["body"]
        labels = {"body": ""}
        widgets = {
            "body": forms.Textarea(attrs={"rows": 4, "cols": 130}),
        }

tasks/views.py
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from tasks.models import Task
from django.views.decorators.http import require_http_methods
from datetime import datetime
from tasks.models import STATUS_CHOICES
from tasks.forms import CommentForm


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/new.html"
    fields = ["name", "project", "start_date", "due_date", "assignee", "notes"]

    def get_success_url(self) -> str:
        return reverse_lazy("show_project", args=[self.object.project.id])


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["STATUS_CHOICES"] = STATUS_CHOICES
        return context

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


@require_http_methods(["POST"])
def complete_task(request, pk):
    if request.method == "POST":
        task = Task.objects.get(id=pk)
        task.is_completed = True
        task.date_completed = datetime.now()
        task.status = "CLOSED"
        task.save()
    return redirect("show_my_tasks")


def update_status(request, pk):
    if request.method == "POST":
        task = Task.objects.get(id=pk)
        task.status = request.POST.get("updated_status")
        if task.status in ["DROPPED", "COMPLETED", "CLOSED"]:
            task.is_completed = True
            task.date_completed = datetime.now()
        elif task.status in [
            "OPEN",
            "IN PROGRESS",
            "PENDING",
            "NEEDS FOLLOW UP",
        ]:
            task.is_completed = False
            task.date_completed = None
        task.save()
    return redirect("show_my_tasks")


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    template_name = "tasks/edit.html"
    fields = [
        "name",
        "start_date",
        "due_date",
        "is_completed",
        "date_completed",
        "project",
        "assignee",
        "notes",
        "status",
        "priority",
    ]
    success_url = reverse_lazy("show_my_tasks")
    # def get_success_url(self) -> str:
    #     return reverse_lazy("")

    # We want other people to be able to edit other people's task
    # (e.g. manager updating managee's task)
    # def get_queryset(self):
    #     return Task.objects.filter(assignee=self.request.user)


class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task
    template_name = "tasks/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["comment_form"] = CommentForm()

        return context

    # We want other people to be able to view other people's task details
    # (e.g. manager viewing and commenting on managee's task, or even teammates)
    # def get_queryset(self):
    #     return Task.objects.filter(assignee=self.request.user)


def post_comment(request, pk):
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.task = Task.objects.get(pk=pk)
            comment.commenter = request.user
            comment.save()
    return redirect("show_task", pk=pk)


def search_task(request):
    """search function"""
    if request.method == "POST":
        query_name = request.POST.get("name", None)
        tasks = Task.objects.all()
        if query_name:
            results = Task.objects.filter(name__contains=query_name)
            return render(
                request,
                "tasks/task_search.html",
                {
                    "results": results,
                    "STATUS_CHOICES": STATUS_CHOICES,
                    "query_name": query_name,
                }
                # request,
                # "tasks/list.html",
                # {"results": results, "tasks": tasks},
            )

    return render(request, "tasks/task_search.html")
    # return render(request, "tasks/list.html")

tasks/templates/tasks/detail.html
{% extends 'base.html' %}
{% load markdownify %}

{% block content %}
    <main>
        <div class="project-detail">
            <div>
                <div class="taskdetailheader taskdetailheader-container">
                    <div>
                        <ul>
                            <li>
                                <p>Status</p>
                                <p>{{ task.status }}</p>
                            </li>
                            <li>
                                <p>Assignee</p>
                                <p>{{ task.assignee }}</p>
                            </li>
                            <li>
                                <p>Priority</p>
                                <p>{{ task.priority }}</p>
                            </li>
                            <li>
                                <p>Project</p>
                                <p>{{ task.project }}</p>
                            </li>
                        </ul>
                    </div>
                    <div>
                        <ul>
                            <li>
                                <p>Start date</p>
                                <p>{{ task.start_date|date:"M d, Y" }}</p>
                            </li>
                            <li>
                                <p>Due date</p>
                                <p>{{ task.due_date|date:"M d, Y" }}</p>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <h1>{{ task.name }}</h1>
            <p>
                <a href="{% url 'update_task' task.id %}">Edit Task</a>
            </p>
            <div>



            </div>

            <div>
                {% if task.notes %}
                    <h2>Notes:</h2>
                    <p>{{ task.notes|markdownify }}</p>
                {% else %}
                    <h2>Notes:</h2>
                    <p>There are no notes on this task yet</p>
                {% endif %}
            </div>
            <div>
                <h2>Comments</h2>
                <form method="post" action="{% url 'post_comment' task.id %}">
                    {% csrf_token %}
                    {{ comment_form.as_p }}
                        {% comment %}
                        This is a way to hardcode the {{comment_form.as_p}} so "Body" label doesn't show on page to user
                        <p>
                        <label for="id_body"></label>
                        <textarea name="body" cols="120" rows="4" required id="id_body"></textarea>
                        </p>
                        {% endcomment %}
                    <button>Post Comment</button>
                </form>
                <div class="all-comments-container">
                    {% for comment in task.comments.all %}
                        <div class="comment-header">
                            <div class="comment-commenter">{{ comment.commenter }}</div>
                            <div class="comment-created">{{ comment.created_on|date:"F j, Y" }} at {{ comment.created_on|time:"g:i a" }}</div>
                        </div>
                        <p class="comment-body">{{ comment.body }}</p>
                    {% empty %}
                        <p>No comments yet</p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

tasks/templates/tasks/edit.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div class="task-form">
            <h1>Update Task: {{ task.name }}</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div>
                    <button>Update</button>
                </div>
            </form>
        </div>
    </main>
{% endblock content %}

tasks/templates/tasks/list.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div class="my-tasks-list">
            <h1>My Tasks</h1>
            <div>
                <form action="{% url 'search_task' %}" method="POST">
                    {% csrf_token %}
                    <input type="text" name="name">
                    {% comment %} <input type="submit" name="submit" value="Search"> {% endcomment %}
                    <button type="submit">Search</button>
                </form>
                {% comment %} {% for result in results %}
                    <p>
                        <a href="{% url 'show_task' result.id %}">{{ result.name }}</a>
                    </p>
                {% endfor %} {% endcomment %}
            </div>
            <p>
                <a href="{% url 'create_task' %}">Create a new task</a>
            </p>
            {% if task_list %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Project</th>
                            <th>Start Date</th>
                            <th>Due Date</th>
                            <th>Is Closed</th>
                            <th>Date Closed</th>
                            <th>Status</th>
                            <th>Priority</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in task_list %}
                            <tr>
                                <td>
                                    <a href="{% url 'show_task' task.id %}">{{ task.name }}</a>
                                </td>
                                <td>{{ task.project }}</td>
                                <td>{{ task.start_date|date:"M d, Y" }}</td>
                                <td>{{ task.due_date|date:"M d, Y" }}</td>
                                <td>
                                    {% if task.is_completed %}
                                        Closed
                                    {% else %}
                                        <form method="post" action="{% url 'complete_task' task.id %}">
                                            {% csrf_token %}
                                            <input type="hidden" name="is_completed" value="True">
                                            <button>Close</button>
                                        </form>
                                    {% endif %}
                                </td>
                                <td>{{ task.date_completed|date:"M d, Y"|default_if_none:"" }}</td>
                                {% comment %} <td>{{ task.status }}</td> {% endcomment %}
                                <td>
                                    <form method="post" action="{% url 'update_status' task.id %}">
                                        {% csrf_token %}
                                        <select name="updated_status">
                                        {% for choice in STATUS_CHOICES %}
                                            {% if choice.0 == task.status %}
                                                <option value="{{ choice.0 }}" selected>{{ choice.0 }}</option>
                                            {% else %}
                                                <option value="{{ choice.0 }}">{{ choice.0 }}</option>
                                            {% endif %}
                                        {% endfor %}
                                        </select>
                                        <button type="submit">Update</button>
                                    </form>
                                </td>
                                <td>{{ task.priority }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>You have no tasks</p>
            {% endif %}
        </div>
    </main>
{% endblock content %}

tasks/templates/tasks/new.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div class="task-form">
            <h1>Create a new task</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div>
                    <button>Create</button>
                </div>
            </form>
        </div>
    </main>
{% endblock content %}

tasks/templates/tasks/task_search.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div class="my-tasks-list">
            <h1>My Tasks - Search Results for: "{{ query_name }}"</h1>
            <div>
                <form action="{% url 'search_task' %}" method="POST">
                    {% csrf_token %}
                    <input type="text" name="name">
                    {% comment %} <input type="submit" name="submit" value="Search"> {% endcomment %}
                    <button type="submit">Search</button>
                </form>
            </div>
            <p>
                <a href="{% url 'create_task' %}">Create a new task</a>
            </p>
            {% if results %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Project</th>
                            <th>Start Date</th>
                            <th>Due Date</th>
                            <th>Is Completed</th>
                            <th>Date Completed</th>
                            <th>Status</th>
                            <th>Priority</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for result in results %}
                            <tr>
                                <td>
                                    <a href="{% url 'show_task' result.id %}">{{ result.name }}</a>
                                </td>
                                <td>{{ result.project }}</td>
                                <td>{{ result.start_date|date:"M d, Y" }}</td>
                                <td>{{ result.due_date|date:"M d, Y" }}</td>
                                <td>
                                    {% if result.is_completed %}
                                        Done
                                    {% else %}
                                        <form method="post" action="{% url 'complete_task' result.id %}">
                                            {% csrf_token %}
                                            <input type="hidden" name="is_completed" value="True">
                                            <button>Complete</button>
                                        </form>
                                    {% endif %}
                                </td>
                                <td>{{ result.date_completed|date:"M d, Y"|default_if_none:"" }}</td>
                                {% comment %} <td>{{ task.status }}</td> {% endcomment %}
                                <td>
                                    <form method="post" action="{% url 'update_status' result.id %}">
                                        {% csrf_token %}
                                        <select name="updated_status">
                                        {% for choice in STATUS_CHOICES %}
                                            {% if choice.0 == result.status %}
                                                <option value="{{ choice.0 }}" selected>{{ choice.0 }}</option>
                                            {% else %}
                                                <option value="{{ choice.0 }}">{{ choice.0 }}</option>
                                            {% endif %}
                                        {% endfor %}
                                        </select>
                                        <button type="submit">Update</button>
                                    </form>
                                </td>
                                <td>{{ result.priority }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <h3>There are no Tasks that match your search</h3>
            {% endif %}
        </div>
    </main>
{% endblock content %}