projects/urls.py
from django.urls import path
from projects.views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
    search_project,
)


urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
    path("search/", search_project, name="search_project"),
]

tasks/urls.py
from django.urls import path
from tasks.views import (
    TaskCreateView,
    TaskListView,
    complete_task,
    update_status,
    TaskUpdateView,
    TaskDetailView,
    post_comment,
    search_task,
)


urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", complete_task, name="complete_task"),
    path("<int:pk>/status/", update_status, name="update_status"),
    path("<int:pk>/edit/", TaskUpdateView.as_view(), name="update_task"),
    path("<int:pk>/", TaskDetailView.as_view(), name="show_task"),
    path("<int:pk>/comment/", post_comment, name="post_comment"),
    path("search/", search_task, name="search_task"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
]

projects/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField(USER_MODEL, related_name="projects")

    def __str__(self):
        return self.name

projects/views.py
from django.urls import reverse_lazy
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from projects.models import Project


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # This is when I had calculated the completion rate in the view
        # completion_rate_per_project = {}
        # for project in Project.objects.all():
        #     completed_tasks = 0
        #     tasks = project.tasks.all()
        #     for task in tasks:
        #         if task.is_completed == True:
        #             completed_tasks = completed_tasks + 1
        #     # taking care of division by 0
        #     if len(tasks) == 0:
        #         completion_rate_per_project[project.id] = 0
        #     else:
        #         completion_rate_per_project[
        #             project.id
        #         ] = completed_tasks / len(tasks)

        # context["completion_rate_per_project"] = completion_rate_per_project

        # When I couldn't figure out how to display that 0.0-1.0 rate value from above code in % form in the webpage,
        # I found the widthratio Django filter that CALCULATES percentages in addition to displaying them
        # so instead of making the RATE available in the context dictionary,
        # the below makes the NUMBER OF COMPLETED TASKS in the context dictionary
        completed_tasks_per_project = {}
        for project in Project.objects.all():
            completed_tasks = 0
            tasks = project.tasks.all()
            for task in tasks:
                if task.is_completed == True:
                    completed_tasks = completed_tasks + 1

            completed_tasks_per_project[project.id] = completed_tasks

        context["completed_tasks_per_project"] = completed_tasks_per_project

        return context

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        project_completion_status = True
        for task in self.object.tasks.all():
            if task.is_completed == False:
                project_completion_status = False
                break
        context["project_completion_status"] = project_completion_status

        completed_tasks = 0
        tasks = self.object.tasks.all()
        for task in tasks:
            if task.is_completed == True:
                completed_tasks = completed_tasks + 1
        context["completed_tasks"] = completed_tasks

        return context


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/new.html"
    fields = ["name", "description", "members"]

    def get_success_url(self) -> str:
        return reverse_lazy("show_project", args=[self.object.id])


def search_project(request):
    """search function"""
    if request.method == "POST":

        query_name = request.POST.get("name", None)

        completed_tasks_per_project = {}
        for project in Project.objects.all():
            completed_tasks = 0
            tasks = project.tasks.all()
            for task in tasks:
                if task.is_completed == True:
                    completed_tasks = completed_tasks + 1

            completed_tasks_per_project[project.id] = completed_tasks

        projects = Project.objects.all()
        if query_name:
            results = Project.objects.filter(name__contains=query_name)
            return render(
                request,
                "projects/project_search.html",
                {
                    "results": results,
                    "query_name": query_name,
                    "completed_tasks_per_project": completed_tasks_per_project,
                }
                # request,
                # "projects/list.html",
                # {"results": results, "projects": projects},
            )

    return render(request, "projects/project_search.html")
    # return render(request, "projects/list.html")

projects/templates/projects/detail.html
{% extends 'base.html' %}
{% load markdownify %}

{% block content %}
    <main>
        <div class="project-detail">
            <h1>{{ project.name }}</h1>
            {% if project.tasks.all %}
                {% if project_completion_status %}
                    <h2>FINISHED - <span>100% Complete</span></h2>

                {% else %}
                    <h2>ONGOING - <span>{% widthratio completed_tasks project.tasks.all|length 100 %}% Complete</span></h2>

                {% endif %}
            {% else %}
                <h2>IN PLANNING</h2>
            {% endif %}

            <p>{{ project.description|markdownify }}</p>
            <h2>Team Members</h2>
            <ul>
                {% for member in project.members.all %}
                    <li>{{ member }}</li>
                {% endfor %}
            </ul>
            <h2>Tasks</h2>
            <p>
                <a href="{% url 'create_task' %}">Create a new task</a>
            </p>
            {% if project.tasks.all %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Assignee</th>
                            <th>Start date</th>
                            <th>Due date</th>
                            <th>Is completed</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in project.tasks.all %}
                            <tr>
                                <td><a href="{% url 'show_task' task.id %}">{{ task.name }}</a></td>
                                <td>{{ task.assignee }}</td>
                                <td>{{ task.start_date|date:"M d, Y" }}</td>
                                <td>{{ task.due_date|date:"M d, Y" }}</td>
                                <td>{{ task.is_completed|yesno }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>This project has no tasks</p>
            {% endif %}
        </div>
    </main>
{% endblock content %}

projects/templates/projects/list.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div class="project-list">
            <h1>My Projects</h1>
            <div>
                <form action="{% url 'search_project' %}" method="POST">
                    {% csrf_token %}
                    <input type="text" name="name">
                    {% comment %} <input type="submit" name="submit" value="Search"> {% endcomment %}
                    <button type="submit">Search</button>
                </form>
                {% comment %} {% for result in results %}
                    <p>
                        <a href="{% url 'show_project' result.id %}">{{ result.name }}</a>
                    </p>
                {% endfor %} {% endcomment %}
            </div>
            <p>
                <a href="{% url 'create_project' %}">Create a new project</a>
            </p>
            {% if project_list %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Number of tasks</th>
                            <th>Completion %</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for project in project_list %}
                            <tr>
                                <td>
                                    <a href="{% url 'show_project' project.id %}">{{ project.name }}</a>
                                </td>
                                <td>{{ project.tasks.all|length }}</td>
                                {% comment %} <td>{{ completion_rate_per_project[project.id] }}</td> {% endcomment %}
                                {% comment %} <td>
                                    {% for key, value in completion_rate_per_project.items %}
                                        {% if key == project.id %}
                                            {{ value }}
                                        {% endif %}
                                    {% endfor %}
                                </td> {% endcomment %}
                                <td>
                                    {% for key, value in completed_tasks_per_project.items %}
                                        {% if key == project.id %}
                                            {% widthratio value project.tasks.all|length 100 %}%
                                        {% endif %}
                                    {% endfor %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>You are not assigned to any projects</p>
            {% endif %}
        </div>
    </main>
{% endblock content %}

projects/templates/projects/new.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div class="project-form">
            <h1>Create a new project</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div>
                    <button>Create</button>
                </div>
            </form>
        </div>
    </main>
{% endblock content %}

projects/templates/projects/project_search.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div class="project-list">
            <h1>My Projects - Search Results for: "{{ query_name }}"</h1>
            <div>
                <form action="{% url 'search_project' %}" method="POST">
                    {% csrf_token %}
                    <input type="text" name="name">
                    {% comment %} <input type="submit" name="submit" value="Search"> {% endcomment %}
                    <button type="submit">Search</button>
                </form>
            </div>
            <p>
                <a href="{% url 'create_project' %}">Create a new project</a>
            </p>
            {% if results %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Number of tasks</th>
                            <th>Completion %</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for result in results %}
                            <tr>
                                <td>
                                    <a href="{% url 'show_project' result.id %}">{{ result.name }}</a>
                                </td>
                                <td>{{ result.tasks.all|length }}</td>
                                {% comment %} <td>{{ project_completion_rate }}</td> {% endcomment %}
                                <td>
                                    {% for key, value in completed_tasks_per_project.items %}
                                        {% if key == result.id %}
                                            {% widthratio value result.tasks.all|length 100 %}%
                                        {% endif %}
                                    {% endfor %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <h3>There are no Projects that match your search</h3>
            {% endif %}
        </div>
    </main>
{% endblock content %}